#========================================server config=====================================
server:
  port: 9200
#========================================spring config=====================================
spring:
  application:
    name: seata-springcloud-order
  devtools:
    restart:
      enabled: false
#========================================MySQL config=====================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fescardubbo?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
#========================================mybatis config=====================================
mybatis:
  type-aliases-package: com.sly.seata.common.model
  mapper-locations: classpath:mapper/*.xml
#========================================eureka config=====================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://@192.168.7.110:8761/eureka/
